# Generated by Django 5.1.4 on 2025-01-10 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profiles',
            name='username',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
