# Generated by Django 5.1.4 on 2025-01-10 08:21

import django.db.models.deletion
from django.db import migrations, models
import uuid

def convert_id_to_uuid(apps, schema_editor):
    MyModel = apps.get_model('users', 'skill')
    for obj in MyModel.objects.all():
        obj.id = uuid.uuid4()
        obj.save()
        
class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_profiles_location_skill'),
    ]

    # operations = [
    #     migrations.AlterField(
    #         model_name='skill',
    #         name='owner',
    #         field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.profiles'),
    #     ),
    # ]
    operations = [
        migrations.RunPython(convert_id_to_uuid),
    ]