# Generated by Django 5.1.4 on 2025-01-10 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_remove_skill_owner'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Skill',
        ),
    ]
